# Generated by Django 3.2.2 on 2022-07-29 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveIntegerField(default=1, unique=True, verbose_name='marvel ids')),
                ('title', models.CharField(default='', max_length=120, verbose_name='titles')),
                ('description', models.TextField(default='', verbose_name='descriptions')),
                ('price', models.FloatField(default=0.0, max_length=5, verbose_name='prices')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.URLField(default='', verbose_name='pictures')),
            ],
            options={
                'db_table': 'E Commerce Comic',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=None, verbose_name='Faved')),
                ('cart', models.BooleanField(default=None, verbose_name='On Cart')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished_qty')),
                ('bought_qty', models.PositiveIntegerField(default=0, verbose_name='buied_qty')),
                ('comic', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.comic', verbose_name='Comic')),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'E Commerce Wishlist',
            },
        ),
    ]
