# Generated by Django 3.2.2 on 2022-07-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_auto_20220729_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingData',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=120, verbose_name='address')),
                ('province_state', models.CharField(default='', max_length=120, verbose_name='province_state')),
                ('country', models.CharField(default='', max_length=120, verbose_name='country')),
                ('postal_code', models.CharField(default='', max_length=120, verbose_name='postal_code')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='stars',
            field=models.PositiveIntegerField(default=0, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='comic',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.comic', verbose_name='Comic'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_data',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.shippingdata', verbose_name='Shipping Data'),
        ),
    ]
