# Generated by Django 3.2.2 on 2022-07-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20220729_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shipping_data',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.shippingdata', verbose_name='Shipping Data'),
        ),
    ]
