# Generated by Django 3.2.2 on 2022-08-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20220729_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_qty',
            new_name='on_cart_qty',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='bought_qty',
        ),
    ]
