# Generated by Django 3.2.2 on 2022-08-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('ecommerce', '0009_auto_20220817_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAPIKey',
            fields=[
                ('apikey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rest_framework_api_key.apikey')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
            bases=('rest_framework_api_key.apikey',),
        ),
    ]
